export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const LOAD_USER_1 = 'LOAD_USER_1';

export const UPDATE_SEARCH_USERNAME_FIELD = 'UPDATE_SEARCH_USERNAME_FIELD';