export const LOAD_USER_1 = 'LOAD_USER_1';
export const SEARCH_USER_1 = 'SEARCH_USER_1';
export const SEARCH_USER_2 = 'SEARCH_USER_2';
export const UPDATE_SEARCH_USERNAME_FIELD = 'UPDATE_SEARCH_USERNAME_FIELD';
